/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TeamJsonld} from "./teamJsonld";

export interface GameJsonld {
    readonly context?: string;
    readonly type?: string;
    readonly id?: number;
    readonly '@id': string;
    datetime?: String;
    scoreHome: number;
    scoreAway: number;
    teamHome: TeamJsonld;
    teamAway: TeamJsonld;
}