/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HydraSearch, HydraView, PlayerJsonld } from './';

export interface HydraPlayer {
    'hydra:member': Array<PlayerJsonld>;
    'hydra:totalItems'?: number;
    hydraview?: HydraView;
    hydrasearch?: HydraSearch;
}