/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {PlayerJsonld} from "./playerJsonld";

export interface TeamJsonld {
    readonly '@id': string;
    readonly context?: string;
    readonly id?: string;
    readonly type?: string;
    name?: string;
    player1: PlayerJsonld;
    player2?: PlayerJsonld;
}